### ISSUE TITLE
Empty release archives for 0.6.4 ?

### ISSUE THREAD

**Issue by rinopo** [usualoma/mt-plugin-QuickRebuild#3]
こちらのリリースページにある version 0.6.4 のアーカイブ・ファイルの中身が空のようです。👀 

https://github.com/usualoma/mt-plugin-QuickRebuild/releases
![161004](https://cloud.githubusercontent.com/assets/45791/19068809/1569858e-8a5f-11e6-9494-7326065241e0.png)

**Comment by usualoma** [comment]
ありがとうございます！
直しました！
https://github.com/usualoma/mt-plugin-QuickRebuild/releases/tag/v0.6.4

**Comment by rinopo** [comment]
@usualoma 
こちらこそ、ありがとうございます!
